param(
    [string]$ProgramName = "TSKSTATUS",
    [string]$OutputPath,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptRoot

function Resolve-ProjectPath {
    param([string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }
    return Join-Path $projectRoot $Path
}

function Assert-ProgramName {
    param(
        [string]$Name,
        [string]$ParameterName,
        [string]$Pattern
    )

    if ($Name -notmatch $Pattern) {
        throw "$ParameterName '$Name' must match $Pattern."
    }
}

Assert-ProgramName -Name $ProgramName -ParameterName "ProgramName" -Pattern '^[A-Z][A-Z0-9_]{1,30}$'

if (-not $OutputPath) {
    $OutputPath = "generated\karel\$ProgramName.KL"
}
$resolvedOutputPath = Resolve-ProjectPath $OutputPath

if ((Test-Path -LiteralPath $resolvedOutputPath) -and -not $Force) {
    throw "KAREL source already exists: $resolvedOutputPath. Use -Force to overwrite."
}

$lines = @(
    "PROGRAM $ProgramName",
    "%NOLOCKGROUP",
    "%ENVIRONMENT REGOPE",
    "%COMMENT = 'AI task state helper'",
    "",
    "-- Generated by tools\New-FanucTaskStateKarelSource.ps1.",
    "-- Purpose: read task state only; do not run, pause, abort, or move anything.",
    "-- TP usage: CALL $ProgramName('TASK_NAME', result_register).",
    "-- Example:  CALL $ProgramName('F_FLEXI_LOADER',91).",
    "",
    "-- Result register block:",
    "--   R[base]   = normalized task state",
    "--   R[base+1] = raw TSK_STATUS value",
    "--   R[base+2] = task number",
    "--   R[base+3] = current executing line number, or 0",
    "--   R[base+4] = KAREL status from first GET_TSK_INFO / parameter read",
    "",
    "-- Normalized task state:",
    "--    10 = run accepted",
    "--    20 = running",
    "--    30 = paused",
    "--    40 = aborted / not running",
    "--    50 = aborting",
    "--   901 = missing or invalid CALL parameter",
    "--   900 = GET_TSK_INFO failed",
    "--   999 = unrecognized raw task status",
    "",
    "VAR",
    "  task_name : STRING[32]",
    "  task_no : INTEGER",
    "  base_reg : INTEGER",
    "  data_type : INTEGER",
    "  value_int : INTEGER",
    "  dummy_int : INTEGER",
    "  dummy_real : REAL",
    "  value_str : STRING[32]",
    "  dummy_str : STRING[32]",
    "  status : INTEGER",
    "  set_status : INTEGER"
)

$lines += @(
    "",
    "ROUTINE write_int(reg_no : INTEGER; value : INTEGER)",
    "BEGIN",
    "  SET_INT_REG(reg_no, value, set_status)",
    "END write_int",
    "",
    "ROUTINE write_block(result : INTEGER; raw_status : INTEGER; task_number : INTEGER; line_no : INTEGER; karel_status : INTEGER)",
    "BEGIN",
    "  write_int(base_reg, result)",
    "  write_int(base_reg + 1, raw_status)",
    "  write_int(base_reg + 2, task_number)",
    "  write_int(base_reg + 3, line_no)",
    "  write_int(base_reg + 4, karel_status)",
    "END write_block",
    "",
    "BEGIN",
    "  task_name = ''",
    "  task_no = 0",
    "  base_reg = 0",
    "  data_type = 0",
    "  value_int = 0",
    "  dummy_int = 0",
    "  dummy_real = 0",
    "  value_str = ''",
    "  dummy_str = ''",
    "  status = 0",
    "",
    "  GET_TPE_PRM(2, data_type, base_reg, dummy_real, dummy_str, status)",
    "  IF (status <> 0) OR (data_type <> 1) OR (base_reg <= 0) THEN",
    "    WRITE('$ProgramName invalid result register parameter', CR)",
    "  ELSE",
    "    GET_TPE_PRM(1, data_type, dummy_int, dummy_real, task_name, status)",
    "    IF (status <> 0) OR (data_type <> 3) THEN",
    "      write_block(901, 0, 0, 0, status)",
    "    ELSE",
    "  GET_TSK_INFO(task_name, task_no, TSK_STATUS, value_int, value_str, status)",
    "",
    "  IF status <> 0 THEN",
    "        write_block(900, 0, task_no, 0, status)",
    "  ELSE",
    "        write_int(base_reg + 1, value_int)",
    "        write_int(base_reg + 2, task_no)",
    "        write_int(base_reg + 4, status)",
    "",
    "    IF value_int = PG_RUNACCEPT THEN",
    "          write_int(base_reg, 10)",
    "    ELSE",
    "      IF value_int = PG_RUNNING THEN",
    "            write_int(base_reg, 20)",
    "      ELSE",
    "        IF value_int = PG_PAUSED THEN",
    "              write_int(base_reg, 30)",
    "        ELSE",
    "          IF value_int = PG_ABORTED THEN",
    "                write_int(base_reg, 40)",
    "          ELSE",
    "            IF value_int = PG_ABORTING THEN",
    "                  write_int(base_reg, 50)",
    "            ELSE",
    "                  write_int(base_reg, 999)",
    "            ENDIF",
    "          ENDIF",
    "        ENDIF",
    "      ENDIF",
    "    ENDIF",
    "",
    "    GET_TSK_INFO(task_name, task_no, TSK_LINENUM, value_int, value_str, status)",
    "    IF status = 0 THEN",
    "          write_int(base_reg + 3, value_int)",
    "    ELSE",
    "          write_int(base_reg + 3, 0)",
    "    ENDIF"
)

$lines += @(
    "      ENDIF",
    "    ENDIF",
    "  ENDIF",
    "END $ProgramName"
)

$parent = Split-Path -Parent $resolvedOutputPath
if (-not (Test-Path -LiteralPath $parent)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
}

$source = $lines -join "`r`n"
Set-Content -LiteralPath $resolvedOutputPath -Value $source -Encoding ASCII

[pscustomobject]@{
    ProgramName = $ProgramName
    OutputPath = (Get-Item -LiteralPath $resolvedOutputPath).FullName
    Interface = "CALL $ProgramName('TASK_NAME', result_register)"
}
