param(
    [string]$ProgramName = "A_TSKSTAT",
    [string]$TargetTask = "F_FLEXI_LOADER",
    [string]$OutputPath,
    [int]$ResultRegister = 91,
    [int]$RawStatusRegister = 92,
    [int]$TaskNumberRegister = 93,
    [int]$LineNumberRegister = 94,
    [int]$KarelStatusRegister = 95,
    [int]$ProgramNameStringRegister = 0,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptRoot

function Resolve-ProjectPath {
    param([string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }
    return Join-Path $projectRoot $Path
}

function Assert-ProgramName {
    param(
        [string]$Name,
        [string]$ParameterName,
        [string]$Pattern
    )

    if ($Name -notmatch $Pattern) {
        throw "$ParameterName '$Name' must match $Pattern."
    }
}

Assert-ProgramName -Name $ProgramName -ParameterName "ProgramName" -Pattern '^A_[A-Z0-9_]{1,30}$'
Assert-ProgramName -Name $TargetTask -ParameterName "TargetTask" -Pattern '^[A-Z][A-Z0-9_]{1,30}$'

foreach ($entry in @(
    @{ Name = "ResultRegister"; Value = $ResultRegister },
    @{ Name = "RawStatusRegister"; Value = $RawStatusRegister },
    @{ Name = "TaskNumberRegister"; Value = $TaskNumberRegister },
    @{ Name = "LineNumberRegister"; Value = $LineNumberRegister },
    @{ Name = "KarelStatusRegister"; Value = $KarelStatusRegister }
)) {
    if ([int]$entry.Value -lt 1) {
        throw "$($entry.Name) must be positive."
    }
}

if ($ProgramNameStringRegister -lt 0) {
    throw "ProgramNameStringRegister must be 0 or positive."
}

if (-not $OutputPath) {
    $OutputPath = "generated\karel\$ProgramName.KL"
}
$resolvedOutputPath = Resolve-ProjectPath $OutputPath

if ((Test-Path -LiteralPath $resolvedOutputPath) -and -not $Force) {
    throw "KAREL source already exists: $resolvedOutputPath. Use -Force to overwrite."
}

$stringRegisterConst = ""
$stringRegisterWrite = ""
if ($ProgramNameStringRegister -gt 0) {
    $stringRegisterConst = "  REG_PROGRAM_NAME = $ProgramNameStringRegister"
    $stringRegisterWrite = @"
    GET_TSK_INFO(task_name, task_no, TSK_PROGNAME, value_int, value_str, status)
    IF status = 0 THEN
      SET_STR_REG(REG_PROGRAM_NAME, value_str, set_status)
    ENDIF
"@
}

$lines = @(
    "PROGRAM $ProgramName",
    "%NOLOCKGROUP",
    "%ENVIRONMENT REGOPE",
    "%COMMENT = 'AI task state helper'",
    "",
    "-- Generated by tools\New-FanucTaskStateKarelSource.ps1.",
    "-- Purpose: read task state only; do not run, pause, abort, or move anything.",
    "",
    "CONST",
    "  TARGET_TASK = '$TargetTask'",
    "  REG_RESULT = $ResultRegister",
    "  REG_RAW_STATUS = $RawStatusRegister",
    "  REG_TASK_NO = $TaskNumberRegister",
    "  REG_LINE_NO = $LineNumberRegister",
    "  REG_KAREL_STATUS = $KarelStatusRegister"
)

if ($stringRegisterConst) {
    $lines += $stringRegisterConst
}

$lines += @(
    "",
    "-- Normalized result written to REG_RESULT:",
    "--   10 = run accepted",
    "--   20 = running",
    "--   30 = paused",
    "--   40 = aborted / not running",
    "--   50 = aborting",
    "--  900 = GET_TSK_INFO failed",
    "--  999 = unrecognized raw task status",
    "",
    "VAR",
    "  task_name : STRING[32]",
    "  task_no : INTEGER",
    "  value_int : INTEGER",
    "  value_str : STRING[32]",
    "  status : INTEGER",
    "  set_status : INTEGER",
    "",
    "ROUTINE write_int(reg_no : INTEGER; value : INTEGER)",
    "BEGIN",
    "  SET_INT_REG(reg_no, value, set_status)",
    "END write_int",
    "",
    "BEGIN",
    "  task_name = TARGET_TASK",
    "  task_no = 0",
    "  value_int = 0",
    "  value_str = ''",
    "  status = 0",
    "",
    "  GET_TSK_INFO(task_name, task_no, TSK_STATUS, value_int, value_str, status)",
    "  write_int(REG_KAREL_STATUS, status)",
    "  write_int(REG_TASK_NO, task_no)",
    "",
    "  IF status <> 0 THEN",
    "    write_int(REG_RESULT, 900)",
    "    write_int(REG_RAW_STATUS, 0)",
    "    write_int(REG_LINE_NO, 0)",
    "  ELSE",
    "    write_int(REG_RAW_STATUS, value_int)",
    "",
    "    IF value_int = PG_RUNACCEPT THEN",
    "      write_int(REG_RESULT, 10)",
    "    ELSE",
    "      IF value_int = PG_RUNNING THEN",
    "        write_int(REG_RESULT, 20)",
    "      ELSE",
    "        IF value_int = PG_PAUSED THEN",
    "          write_int(REG_RESULT, 30)",
    "        ELSE",
    "          IF value_int = PG_ABORTED THEN",
    "            write_int(REG_RESULT, 40)",
    "          ELSE",
    "            IF value_int = PG_ABORTING THEN",
    "              write_int(REG_RESULT, 50)",
    "            ELSE",
    "              write_int(REG_RESULT, 999)",
    "            ENDIF",
    "          ENDIF",
    "        ENDIF",
    "      ENDIF",
    "    ENDIF",
    "",
    "    GET_TSK_INFO(task_name, task_no, TSK_LINENUM, value_int, value_str, status)",
    "    IF status = 0 THEN",
    "      write_int(REG_LINE_NO, value_int)",
    "    ELSE",
    "      write_int(REG_LINE_NO, 0)",
    "    ENDIF"
)

if ($stringRegisterWrite) {
    $lines += $stringRegisterWrite -split "`r?`n"
}

$lines += @(
    "  ENDIF",
    "END $ProgramName"
)

$parent = Split-Path -Parent $resolvedOutputPath
if (-not (Test-Path -LiteralPath $parent)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
}

$source = $lines -join "`r`n"
Set-Content -LiteralPath $resolvedOutputPath -Value $source -Encoding ASCII

[pscustomobject]@{
    ProgramName = $ProgramName
    TargetTask = $TargetTask
    OutputPath = (Get-Item -LiteralPath $resolvedOutputPath).FullName
    ResultRegister = $ResultRegister
    RawStatusRegister = $RawStatusRegister
    TaskNumberRegister = $TaskNumberRegister
    LineNumberRegister = $LineNumberRegister
    KarelStatusRegister = $KarelStatusRegister
    ProgramNameStringRegister = $ProgramNameStringRegister
}
